version: "3"
services:
  database:
    image: "postgres"
    container_name: "postgres_argel"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pizzaria
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data